# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Lint App with Deno / Build and test Angular App with Angular ng test/karma

on:
  workflow_dispatch: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: 
      name: workflow
      url: https://github.com
    env:
      ON_GITHUB_RUNNER: true

    defaults:
      run:
        working-directory: ./my-resume-app

    strategy:
      matrix:
        node-version: ['22.x']

    steps: 
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: set FIREBASE_CONFIG from GitHub secret
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          mkdir secrets;
          cat << EOF > ./secrets/firebase-config.ts
          import { FirebaseOptions } from 'firebase/app';
          export const firebaseConfig: FirebaseOptions = {
             $(echo "$FIREBASE_CONFIG")
          };
          EOF

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: install node dependencies with npm ci
        run: npm ci -c workflow

      - name: build the Angular project with npm
        # run if a script in package.json is present
        run: npm run workflow-build --if-present

      - name: test Angular project
        run: npm run workflow-test
