# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

# Workflow Notes
# 1. Workflow defines a single job named `test`
# 2. Uses a custom environment named `workflow` running on `ubuntu-latest`
# 3. Sets environment variables for debug tests on GitHub runners / App Check debug token
# 4. Runs linting with Deno first to stop if there are any detectable code quality issues
# 5. Runs `npm ci` for a clean install of node dependencies
# 6. Run `npm run workflow-test` to build Angular project and run CI tests
# 7. Uses FirebaseExtended/action-hosting-deploy to deploy the project to the Firebase live channel (production)

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: workflow
      url: https://console.firebase.google.com/
    env:
      FIREBASE_APPCHECK_DEBUG_TOKEN: ${{ secrets.FIREBASE_APPCHECK_DEBUG_TOKEN_FOR_CI }}

    defaults:
      run:
        working-directory: ./my-resume-app

    strategy:
      matrix:
        node-version: ["22.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: set FIREBASE_CONFIG from GitHub secret
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          mkdir -p secrets;
          cat << EOF > ./secrets/firebase-config.ts
          import { FirebaseOptions } from 'firebase/app';
          export const firebaseConfig: FirebaseOptions = {
             $(echo "$FIREBASE_CONFIG")
          };
          EOF

      - name: set APP_CHECK_SITE_KEY from GitHub secret
        env:
          APP_CHECK_SITE_KEY: ${{ secrets.APP_CHECK_SITE_KEY }}
        run: |
          mkdir -p secrets;
          cat << EOF > ./secrets/app-check-config.ts
          export const appCheckSiteKey = $(echo "\"$APP_CHECK_SITE_KEY\"");
          EOF

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: install node dependencies with npm ci
        run: npm ci

      - name: build the Angular project with npm
        run: npm run workflow-build

      - name: test Angular project inside workflow, using mocks for testing Firebase
        run: npm run workflow-test

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RED_PARITY_369703 }}
          channelId: live
          projectId: red-parity-369703
          entryPoint: "./my-resume-app"
