name: Sample shell script workflow

on:
  workflow_dispatch

permissions:
  contents: read

jobs:
  run_echo:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: base

    steps:
      - name: echo hello world
        run: echo "Hello world"
