name: Sample shell script workflow

on:
  workflow_dispatch

jobs:
  run_echo:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: echo hello world
        run: echo "Hello world"
